name: Main

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Set up dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --production
      - name: Build the site
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: .
          production-deploy: true
          deploy-message: Commit ${GITHUB_SHA}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
